# Force redirect from .html to clean URLs (with Pretty URLs enabled)
[[redirects]]
  from = "*.html"
  to = ":splat"
  status = 301!
  force = true

# Your testimonials redirects
[[redirects]]
  from = "/testimonials.html"
  to = "/#testimonials"
  status = 301

[[redirects]]
  from = "/testimonials"
  to = "/#testimonials"
  status = 301