# Force .html removal BEFORE other redirects
[[redirects]]
  from = "https://waldmanelectric.com/*.html"
  to = "https://waldmanelectric.com/:splat"
  status = 301
  force = true

[[redirects]]
  from = "http://waldmanelectric.com/*.html"
  to = "https://waldmanelectric.com/:splat"
  status = 301
  force = true

# Your existing testimonials redirects
[[redirects]]
  from = "/testimonials.html"
  to = "/#testimonials"
  status = 301

[[redirects]]
  from = "/testimonials"
  to = "/#testimonials"
  status = 301

# Serve HTML files when clean URLs are requested
[[redirects]]
  from = "/*"
  to = "/:splat.html"
  status = 200